version : "3.7"
services :
  proyectos-monolitico :
    container_name : proyectos-monolitico
    image : proyectos-monolitico:v1
    build :
      context : .
    ports :
      - "4001:4001"
    networks : 
      - proyectos-app
networks :
  proyectos-app :
